export const startersVegImages: Record<string, number> = {
  "achari_paneer_tikka": require("../../assets/images/starters/veg/achari_paneer_tikka.jpg"),
  "baby_corn_manchurian": require("../../assets/images/starters/veg/baby_corn_manchurian.jpg"),
  "baby_corn_pakoda": require("../../assets/images/starters/veg/baby_corn_pakoda.jpg"),
  "cheese_nuggets": require("../../assets/images/starters/veg/cheese_nuggets.jpg"),
  "chilli_garlic_mushroom": require("../../assets/images/starters/veg/chilli_garlic_mushroom.jpg"),
  "crispy_corn": require("../../assets/images/starters/veg/crispy_corn.jpg"),
  "gobi_manchurian": require("../../assets/images/starters/veg/gobi_manchurian.jpg"),
  "gobi_pakoda": require("../../assets/images/starters/veg/gobi_pakoda.jpg"),
  "harabhara_kabab": require("../../assets/images/starters/veg/harabhara_kabab.jpg"),
  "hariyali_paneer_tikka": require("../../assets/images/starters/veg/hariyali_paneer_tikka.jpg"),
  "malai_brocolli": require("../../assets/images/starters/veg/malai_brocolli.jpg"),
  "malai_paneer_tikka": require("../../assets/images/starters/veg/malai_paneer_tikka.jpg"),
  "manchurian": require("../../assets/images/starters/veg/manchurian.jpg"),
  "mushroom_pakoda": require("../../assets/images/starters/veg/mushroom_pakoda.jpg"),
  "panner_65": require("../../assets/images/starters/veg/panner_65.jpg"),
  "panner_manchurian": require("../../assets/images/starters/veg/panner_manchurian.jpg"),
  "panner_tikka": require("../../assets/images/starters/veg/panner_tikka.jpg"),
  "veg_spring_rolls": require("../../assets/images/starters/veg/veg_spring_rolls.jpg"),
};
