export const startersVegImages: Record<string, number> = {
  "achari_paneer_tikka": require("../../assets/images/starters/veg/achari_paneer_tikka.jpg"),
  "baby_corn_65": require("../../assets/images/starters/veg/baby_corn_65.jpg"),
  "baby_corn_manchurian": require("../../assets/images/starters/veg/baby_corn_manchurian.jpg"),
  "baby_corn_pakoda": require("../../assets/images/starters/veg/baby_corn_pakoda.jpg"),
  "cheese_nuggets": require("../../assets/images/starters/veg/cheese_nuggets.jpg"),
  "chilli_garlic_mushroom": require("../../assets/images/starters/veg/chilli_garlic_mushroom.jpg"),
  "crispy_corn": require("../../assets/images/starters/veg/crispy_corn.jpg"),
  "cut_mirchi": require("../../assets/images/starters/veg/cut_mirchi.jpg"),
  "gobi_manchurian": require("../../assets/images/starters/veg/gobi manchurian.jpg"),
  "gobi_pakoda": require("../../assets/images/starters/veg/gobi pakoda.jpg"),
  "gobi_manchurian": require("../../assets/images/starters/veg/gobi_manchurian.jpg"),
  "gobi_pakoda": require("../../assets/images/starters/veg/gobi_pakoda.jpg"),
  "hara_bhara_kabab": require("../../assets/images/starters/veg/hara_bhara_ kabab.jpg"),
  "hara_bhara_kebab": require("../../assets/images/starters/veg/hara_bhara_kebab.jpg"),
  "harabhara_kabab": require("../../assets/images/starters/veg/harabhara_kabab.jpg"),
  "hariyali_paneer_tikka": require("../../assets/images/starters/veg/hariyali_paneer_tikka.jpg"),
  "malai_brocolli": require("../../assets/images/starters/veg/malai_brocolli.jpg"),
  "malai_paneer_tikka": require("../../assets/images/starters/veg/malai_paneer_tikka.jpg"),
  "malai_tikka": require("../../assets/images/starters/veg/malai_tikka.jpg"),
  "manchurian": require("../../assets/images/starters/veg/manchurian.jpg"),
  "masala_vada": require("../../assets/images/starters/veg/masala_vada.jpg"),
  "medu_vada": require("../../assets/images/starters/veg/medu_vada.jpg"),
  "mirchi_bajji": require("../../assets/images/starters/veg/mirchi_bajji.jpg"),
  "mushroom_pakoda": require("../../assets/images/starters/veg/mushroom_pakoda.jpg"),
  "paneer_65": require("../../assets/images/starters/veg/paneer_65.jpg"),
  "paneer_manchurian": require("../../assets/images/starters/veg/paneer_manchurian.jpg"),
  "paneer_tikka": require("../../assets/images/starters/veg/paneer_tikka.jpg"),
  "panner_65": require("../../assets/images/starters/veg/panner_65.jpg"),
  "panner_manchurian": require("../../assets/images/starters/veg/panner_manchurian.jpg"),
  "panner_tikka": require("../../assets/images/starters/veg/panner_tikka.jpg"),
  "raw_banana_bajji": require("../../assets/images/starters/veg/raw_banana_bajji.jpg"),
  "veg_spring_rolls": require("../../assets/images/starters/veg/veg spring rolls.jpg"),
  "veg_manchurian": require("../../assets/images/starters/veg/veg_manchurian.jpg"),
  "veg_spring_roll": require("../../assets/images/starters/veg/veg_spring_roll.jpg"),
  "veg_spring_rolls": require("../../assets/images/starters/veg/veg_spring_rolls.jpg"),
};
